version: '3.9'

services:
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb
        secrets:
            - db_root_password
            - db_user_password
        environment:
            MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password  
            MYSQL_USER_PASSWORD: /run/secrets/db_user_password
        env_file:
            - .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - my_network
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress
        environment:
            WORDPRESS_DB_USER: ${MYSQL_USER_NAME}
            WORDPRESS_DB_PASSWORD: /run/secrets/db_user_password
            WORDPRESS_DB_NAME: ${MYSQL_DB}
            WORDPRESS_ADMIN_PASSWORD: /run/secrets/wp_admin_password
            WORDPRESS_USER_PASSWORD: /run/secrets/wp_user_password
            REDIS_PASSWORD: /run/secrets/redis_password
        env_file:
            - .env
        secrets:
            - db_user_password
            - wp_admin_password
            - wp_user_password
            - redis_password
        depends_on:
            - redis
            - mariadb
        volumes:
            - wordpress_data:/var/www/html/wordpress
        networks:
            - my_network
        restart: unless-stopped
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/html/wordpress
        networks:
            - my_network
        restart: unless-stopped
    
    redis:
        container_name: redis
        build:
            context: ./requirements/redis
            dockerfile: Dockerfile
        image: redis
        environment:
            REDIS_PASSWORD: /run/secrets/redis_password
        secrets:
            - redis_password
        networks:
            - my_network
        restart: unless-stopped
    
    ftp-server:
        container_name: ftp-server
        build:
            context: ./requirements/ftp-server
            dockerfile: Dockerfile
        image: ftp-server
        networks:
            - my_network
        restart: unless-stopped
        depends_on:
            - wordpress
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        environment:
            FTP_PASSWORD: /run/secrets/ftp_password
        env_file:
            - .env
        volumes:
            - wordpress_data:/srv/ftpfiles
        secrets:
            - ftp_password

secrets:
    db_root_password:
        file: ../secrets/db_root_password.txt
    db_user_password:
        file: ../secrets/db_user_password.txt
    wp_admin_password:
        file: ../secrets/wp_admin_password.txt
    wp_user_password:
        file: ../secrets/wp_user_password.txt
    redis_password:
        file: ../secrets/redis_password.txt
    ftp_password:
        file: ../secrets/ftp_password.txt

volumes:
    mariadb_data:
        name: mariadb_data
        driver: local
        driver_opts:
            type: none
            device: /home/nnomenja/data/mysql
            o: bind

    wordpress_data:
        name: wordpress_data
        driver: local
        driver_opts:
            type: none
            device: /home/nnomenja/data/wordpress
            o: bind
    
networks:
    my_network:
        driver: bridge